spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others:true
  datasource:
    url: jdbc:h2:mem:test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  redis:
    host: localhost
    port: 6379
  security:

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret-key: ato12345678910fghgjkliygfbfghjhggjytdfdgbcnvjhhgjgyfthato12345678910fghgjkliygfbfghjhggjytdfdgbcnvjhhgjgyfthato12345678910fghgjkliygfbfghjhggjytdfdgbcnvjhhgjgyfthato123456789>
  access-token-expiration-minutes: 1440
  refresh-token-expiration-minutes: 1440

mail:
  address:
    admin: admin@email.com

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace