name: join server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: join-deploy

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./server

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
    
    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: ${{ env.working-directory }}

    - name: Make Directory
      run: mkdir -p deploy
        
    - name: Copy Jar
      run: cp server/./build/libs/*.jar ./deploy
      
    - name: Copy appspec.yml
      run: cp server/appspec.yml ./deploy

    - name: Copy script
      run: cp server/./scripts/*.sh ./deploy

    - name: Make zip file
      run: zip -r ./join.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./join.zip s3://$S3_BUCKET_NAME/
    
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name join \
        --deployment-group-name join-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=join-deploy,bundleType=zip,key=join.zip \ 
        --region ap-northeast-2
